{
	"version": 1788730601,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/back_1-sheet0.png",
		"images/back_2-sheet0.png",
		"images/camera-sheet0.png",
		"images/sprite-sheet0.png",
		"images/arrow_im-sheet0.png",
		"images/3dgarro-sheet0.png",
		"images/rain_sound-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/off_button-sheet0.png",
		"images/end_back-sheet0.png",
		"images/screen_fx-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/window-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/close_button-sheet0.png",
		"images/close_button-sheet1.png",
		"images/close_button-sheet2.png",
		"images/ti_text-sheet0.png",
		"images/mask-sheet0.png",
		"images/mask-sheet1.png",
		"images/down_panel-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/start_button-sheet0.png",
		"images/folder_1-sheet0.png",
		"images/windy-sheet0.png",
		"images/windy-sheet1.png",
		"images/windy-sheet2.png",
		"images/windy_bob-sheet0.png",
		"images/ok_button-sheet0.png",
		"images/lamp-sheet0.png",
		"images/total_delete-sheet0.png",
		"images/deleted-sheet0.png",
		"images/image-sheet0.png",
		"images/image-sheet1.png",
		"images/total_type-sheet0.png",
		"images/total_locked-sheet0.png",
		"images/total_drivers-sheet0.png",
		"images/face-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/eye_center-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/hum (1).m4a",
		"media/hum (1).ogg",
		"media/rain.m4a",
		"media/rain.ogg",
		"media/off (2).m4a",
		"media/off (2).ogg",
		"media/on_hum.m4a",
		"media/on_hum.ogg",
		"media/open.m4a",
		"media/open.ogg",
		"media/jg-032316-sfx-cat-meow-vhs.m4a",
		"media/jg-032316-sfx-cat-meow-vhs.ogg",
		"media/windows xp startup.m4a",
		"media/windows xp startup.ogg",
		"media/win_error.m4a",
		"media/win_error.ogg",
		"media/rebnok-ryidaet-isterika.m4a",
		"media/rebnok-ryidaet-isterika.ogg",
		"media/packet-radio-simple-stardado.ogg",
		"media/elevenlabs_2026-09-06t20_06_25_joseph ortman - deep & raspy_pvc_sp73_s30_sb50_f2-vhs.m4a",
		"media/elevenlabs_2026-09-06t20_06_25_joseph ortman - deep & raspy_pvc_sp73_s30_sb50_f2-vhs.ogg",
		"media/michael_jackson_-_beat_it_47829974-vhs.m4a",
		"media/michael_jackson_-_beat_it_47829974-vhs.ogg",
		"media/amirthetrash_-_frutiger_aero_80801595-vhs.m4a",
		"media/amirthetrash_-_frutiger_aero_80801595-vhs.ogg",
		"media/elevenlabs_2026-09-06t20_00_51_joseph ortman - deep & raspy_pvc_sp81_s30_sb50_f2-vhs.m4a",
		"media/elevenlabs_2026-09-06t20_00_51_joseph ortman - deep & raspy_pvc_sp81_s30_sb50_f2-vhs.ogg",
		"media/ost (1).m4a",
		"media/ost (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}